services:
  - type: pserv
    name: isp-manager-db
    plan: free
    postgresVersion: "16"
    
  - type: web
    name: isp-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.14"
    databases:
      - name: isp-manager-db
        databaseName: isp_manager
        user: isp_manager